# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_grabber.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_grabber.proto\x12\x0cimagegrabber\"I\n\x0cImageRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"1\n\rImageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x0cImageGrabber\x12\x44\n\tSendImage\x12\x1a.imagegrabber.ImageRequest\x1a\x1b.imagegrabber.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_grabber_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=37
  _globals['_IMAGEREQUEST']._serialized_end=110
  _globals['_IMAGERESPONSE']._serialized_start=112
  _globals['_IMAGERESPONSE']._serialized_end=161
  _globals['_IMAGEGRABBER']._serialized_start=163
  _globals['_IMAGEGRABBER']._serialized_end=247
# @@protoc_insertion_point(module_scope)
